[2024-08-16T14:42:24.356+0000] {processor.py:186} INFO - Started process (PID=1252) to work on /opt/airflow/dags/__pycache__/first_dag.cpython-312.py
[2024-08-16T14:42:24.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/first_dag.cpython-312.py for tasks to queue
[2024-08-16T14:42:24.359+0000] {logging_mixin.py:190} INFO - [2024-08-16T14:42:24.359+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/first_dag.cpython-312.py
[2024-08-16T14:42:24.383+0000] {logging_mixin.py:190} INFO - [2024-08-16T14:42:24.381+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/__pycache__/first_dag.cpython-312.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
SyntaxError: source code string cannot contain null bytes
[2024-08-16T14:42:24.384+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/first_dag.cpython-312.py
[2024-08-16T14:42:24.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/first_dag.cpython-312.py took 0.059 seconds
